#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
for installer in $(find . -name install.sh -maxdepth 2); do
    echo "calling installer: \"$installer\""
    sh -c "${installer}" ;
    echo "calling installer: \"$installer\" finished."
done
